### PR TITLE
#7 Fix duplicates in categories.

### PR DESCRIPTION
**Pull request by borisbaldassari**
See Issue #7 for more context. This is the fix to the generated file for ORT.

### CODE REVIEW

**Comment by sschuberth** [comment]
My *guess* is that this needs to be fixed elsewhere, probably in the `master` branch's `src/Generators/OrtLicenseClassificationYml.hs`, as the contents of the `generated` branch are, well, generated.

**Comment by borisbaldassari** [comment]
Thanks @sschuberth for the heads-up. I understand the purpose of a branch named 'generated', but unfortunately I see no way to fix that in the source file; it may be fixed through the generator itself, but that's beyond my understanding. 

My goal was here to share my fix and make it work for people who follow the link in the ort's doc. Please feel free to dismiss the PR, I won't be offended. ;-)

**Comment by sschuberth** [comment]
> Please feel free to dismiss the PR, I won't be offended. ;-)

I'm not a maintainer of this project, nor can I do Haskell, so we're depending on @maxhbr 😉

**Comment by maxhbr** [comment]
Hey, the `generated` branch is generated, yes. I will look into that issue. Thanks for bringing it up

**Comment by maxhbr** [comment]
closed with #9 and also the `generated` branch is regenerated. Can you please confirm that this fixes your issue?

**Comment by borisbaldassari** [comment]
Thanks @maxhbr I confirm that it solves the issue. The generated file can be used by ORT without any error.

Have a wonderful day!

**Pull request closed without merging**
